# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  parrallel: 1


steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'DevOpsProject'
      command: 'buildAndPush'
      repository: 'smnostuff/devopsimage'
      Dockerfile: '**/dockerfile'
  - task: KubernetesManifest@1
    inputs:
      action: 'deploy'
      connectionType: 'AzureResourceManager'
      azureSubscriptionConnection: 'DevOpsSubscription(1571dec2-c2bf-474f-b6f3-815ff9d68f68)'
      azureResourceGroup: 'DevOps'
      kubernetesCluster: 'DevOpsKub'
      manifests: 'application-manifest.yaml'
