# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  parrallel: 1

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'docker hub connection'
      repository: 'smnostuff/devopsimage'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'
  - task: KubernetesManifest@1
    inputs:
      action: 'deploy'
      connectionType: 'azureResourceManager'
      azureSubscriptionConnection: 'Simon Yates DevOps(069aabee-fed9-4d93-8b03-d24c331f52ad)'
      azureResourceGroup: 'DevOpsResource'
      kubernetesCluster: 'DevOpsCluster'
      namespace: 'DevOpsKubernetes'
      manifests: 'application-manifest.yaml'

