# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '3.x'
      includePreviewVersions: true

  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      repository: 'smnostuff/devopsimage'
      tags: 'latest'
      Dockerfile: '**/dockerfile'